version: '3.4'

networks:
  backend:

services:

  sqldata:
    volumes:
    - ./db:/var/opt/mssql/data
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    networks:
      - backend
    ports:
      - 7773:1433 

  apartment.api:
    image: ${DOCKER_REGISTRY-}apartmentapi
    build:
      context: .
      dockerfile: src/ApartmentService/Apartment.API/Dockerfile
    networks:
      - backend

      #----------------------------
  car.api:
    image: ${DOCKER_REGISTRY-}carapi
    build:
      context: .
      dockerfile: src/CarService/Car.API/Dockerfile



      #----------------------------
  school.api:
    image: ${DOCKER_REGISTRY-}schoolapi
    build:
      context: .
      dockerfile: src/SchoolService/School.API/Dockerfile



      #----------------------------
  tourism.api:
    image: ${DOCKER_REGISTRY-}tourismapi
    build:
      context: .
      dockerfile: src/TourismService/Tourism.API/Dockerfile
